### ISSUE TITLE
Network error: Failed to fetch

### ISSUE THREAD

**Issue by LuterOrbs** [Omashu/rf-online-gs-editor#65]
I tried to use the v 1.0.3 but i got this error while signing up
![error](https://user-images.githubusercontent.com/45433298/49169189-555ba900-f34a-11e8-8add-261516b357bf.png)

**Comment by Omashu** [comment]
Sorry bro, v1.0.3 is not up to date.
I will fix it as soon as possible and will release 1.0.4.

**Comment by Omashu** [comment]
Done.
